name: Data Refresh

on:
  [push, pull_request]
  # schedule:
  # - cron: "0 */1 * * *"
jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-22.04
    container:
      image: docker.io/rkrispin/forecast-poc:0.0.0.9001
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Data Refresh
        run: bash data_refresh/eia_data_refresh.sh
        env:
          EIA_API_KEY: ${{ secrets.EIA_API_KEY }}
